version: '3'

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: 'mongodb://mongodb:27017/proyecto_final'
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
