version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      MONGO_URI: 'mongodb://mongodb:27017/proyecto_final'

  frontend:
    build: ./frontend
    ports:
      - '3001:3000'

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
